TwoMutationInitiation = function(BEage,BEonset,firstScreen) {
  # initiation process (Poisson + Exponential)
  # stemcells = rpois(1,X)
  # s.preinitiated = dqrexp(stemcells,mu0)
  # s.preinitiated = s.preinitiated[s.preinitiated<BEage]
  # N.preinitiated = length(s.preinitiated)

  N.preinitiated.expected = X*mu0*BEage
  N.preinitiated = rpois(1,N.preinitiated.expected)
  s.preinitiated = dqrunif(N.preinitiated,0,BEage)

  s.mu1 = dqrexp(N.preinitiated,rate = mu1)
  s.initiated = s.preinitiated+s.mu1
  
  # second and third round (Poisson events generated by pre-initiated cells)
  s.preinitiated = s.initiated[s.initiated < BEage]
  N.preinitiated = length(s.preinitiated)

  s.mu1 = dqrexp(N.preinitiated,rate = mu1)
  s.initiated2 = s.preinitiated+s.mu1
  s.mu1 = dqrexp(N.preinitiated,rate = mu1)
  s.initiated3 = s.initiated2+s.mu1
  
  s.initiated = c(s.initiated[s.initiated < BEage],s.initiated2[s.initiated2 < BEage],
                  s.initiated3[s.initiated3 < BEage])
  N.initiated = length(s.initiated)
  
  # find FTP-transformation across all initiated cells (via minimum order stats)
  out = suppressWarnings(TC1(N.initiated,p,q,mu))
  
  #### FPT lesions  ############################################################
  s.malignant = s.initiated[out$survivor] + out$ftimes[out$survivor]
  # if testing multiple malignancies vs first to arise
  # s.malignant[!which.min(s.malignant)] = Inf

  s.initiated.malignant = s.initiated[out$survivor]
  N.initiated.malignant = length(s.initiated.malignant)
  Y.initiated.malignant = rep(1,N.initiated.malignant)
  
  # determine when transition to HGD occurs
  # all initiated-to-malignant lesions are born LGD
  malign.HGD.transition = BEonset+s.initiated.malignant+HGDconversion(N.initiated.malignant,p.HGD,q.HGD,rho.HGD) 

  # advance any lesions that are born before 1st screen (Svec := time.to.firstScreen)
  Svec = firstScreen - (BEonset+s.initiated.malignant)
  cond = Svec > 0
  if(sum(cond)>0) {
    Svec = Svec[cond]
    Nfwd = length(Svec); Nbwd = N.initiated.malignant - Nfwd
    s.initiated.malignant[ cond] = firstScreen-BEonset
    s.initiated.malignant[!cond] = ceiling(s.initiated.malignant[!cond])
  
    # alphaXsi and p0 vectors for computing the clone sizes after time Svec  
    xsi = (exp(-p*Svec) - exp(-q*Svec))/((q+alpha)*exp(-p*Svec)-(p+alpha)*exp(-q*Svec))
    alphaXsi.vec = alpha*xsi
    top = xsi*(alpha+p)*(alpha+q)*(q*exp(-p*Svec)-p*exp(-q*Svec))
    bot = q*(alpha+p)*exp(-p*Svec) - p*(alpha+q)*exp(-q*Svec)
    p0.vec = top/bot
  
    Y.initiated.malignant[cond] =  genSizeSurvArray(Nfwd,p0.vec,alphaXsi.vec)  # these clones now appear at firstScreen
    Y.initiated.malignant[!cond] = genSizeSurvArray(Nbwd,p0.tau,alphaXsi.tau)
  } else {
    s.initiated.malignant = ceiling(s.initiated.malignant)
    Y.initiated.malignant = genSizeSurvArray(N.initiated.malignant,p0.tau,alphaXsi.tau)
  }

  #### non-FPT lesions #########################################################
  s.initiated.benign = s.initiated[!out$survivor]
  N.initiated.benign = length(s.initiated.benign)
  Y.initiated.benign = rep(1,N.initiated.benign)
  
  # advance any lesions that are born before 1st screen (Svec := time.to.firstScreen)
  Svec = firstScreen - (BEonset+s.initiated.benign)
  cond = Svec > 0
  if(sum(cond)>0) {
    Svec = Svec[cond]
    Nfwd = length(Svec); Nbwd = N.initiated.benign - Nfwd
    s.initiated.benign[ cond] = firstScreen-BEonset
    s.initiated.benign[!cond] = ceiling(s.initiated.benign[!cond])
    
    # alphaXsi and p0 vectors for computing the clone sizes after time Svec
    xsi = (exp(-p*Svec) - exp(-q*Svec))/((q+alpha)*exp(-p*Svec)-(p+alpha)*exp(-q*Svec))
    alphaXsi.vec = alpha*xsi
    top = xsi*(alpha+p)*(alpha+q)*(q*exp(-p*Svec)-p*exp(-q*Svec))
    bot = q*(alpha+p)*exp(-p*Svec) - p*(alpha+q)*exp(-q*Svec)
    p0.vec = top/bot
    
    Y.initiated.benign[cond] =  genSizeSurvArrayWithExtinction(Nfwd,p0.vec,alphaXsi.vec)  # these clones now appear at firstScreen
    Y.initiated.benign[!cond] = genSizeSurvArrayWithExtinction(Nbwd,p0.tau,alphaXsi.tau)
  } else {
    s.initiated.benign = ceiling(s.initiated.benign)
    Y.initiated.benign = genSizeSurvArrayWithExtinction(N.initiated.benign,p0.tau,alphaXsi.tau)
  }
  
  # there are many benign clones - most go extinct in time Svec. Also
  # remove all initiated cells that go to extinction within tau = 6 months (s*0.5) and
  # simulate sizes of survivors within time tau, and then synchronize time evolution
  cond = Y.initiated.benign > 0
  s.initiated.benign = s.initiated.benign[cond]
  N.initiated.benign = length(s.initiated.benign)
  Y.initiated.benign = Y.initiated.benign[cond]
  
  # determine when transition to HGD occurs in 'benign clones (optional)
  # benign.HGD.transition = BEonset+s.initiated.benign+HGDconversion(N.initiated.benign,p.HGD,q.HGD,rho.HGD)
  
  return(list(BenignS = s.initiated.benign,
              BenignN = N.initiated.benign,
              BenignY = Y.initiated.benign,
              MalignS = s.initiated.malignant,
              MalignN = N.initiated.malignant,
              MalignY = Y.initiated.malignant,
              MalignU = malign.HGD.transition,
              FPTs = s.malignant))
}

